import '../globals.css';
import Providers from '@/providers/tanstack-query';
import type { Metadata } from 'next';
import { Kumbh_Sans } from 'next/font/google';

const kumbhSans = Kumbh_Sans({
	variable: '--font-kumbh-sans',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${kumbhSans.variable} ${kumbhSans.style} antialiased`}
			>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
